name: build_access
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  speech_to_text: ^7.3.0
  permission_handler: ^11.0.0
  flutter_tts: ^3.8.0
  camera_android_camerax: ^0.6.26+2
  camera: ^0.11.3
  google_mlkit_text_recognition: ^0.15.1
  flutter_local_ai: ^0.0.6
  get_it: ^9.2.1
  llama_cpp_dart:
    git:
      url: https://github.com/netdur/llama_cpp_dart.git
  dio: ^5.9.2
  path_provider: ^2.1.5
  paddle_ocr: ^0.0.2

dependency_overrides:
  image: ^4.7.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/det.opt
    - assets/models/rec.opt
    - assets/models/cls.opt
    - assets/models/dict.txt